### PR TITLE
Mac OS: fork process when started from a tty

### PR DESCRIPTION
**Pull request by equalsraf**
The goal here is to improve the mac os x fork behavior: https://github.com/equalsraf/neovim-qt/issues/731

I did not have a chance to test this is Mac OS yet, and I dont have an idea for a test here.

### CODE REVIEW

**Comment by equalsraf** [comment]
Tested in Mac OS, --no-fork (or lack of it) now works the same as in other unixes when running from terminal. I still have to check the case when it is not running from a terminal.

**Comment by equalsraf** [comment]
I am done testing. It looks ok, tested from

1. the dock, by pinning a manually started binary
2. by piping /dev/null into nvim-qt stdin

**Comment by jgehrig** [comment]
I'd help test, but I don't own a Mac.

One idea, you could get rid of the `#ifdefs` using the same pattern as `input_*.cpp`. No conditional includes, just a simple function call `bool IsTTYStandardInput()` (with a better name). Implement once for MacOS, and one `_emptyimpl.cpp` for Win32/Unix which always returns false. Share the header definition across all platforms.

Definitely not essential... Feel free to ignore.

I think `#ifdef` is another one of those evils specific to C/C++ software! :wink:

**Comment by equalsraf** [comment]
I agree, but i am inclined to leave it for now.

I think if i were to refactor to remove the ifdefs then i would have to remove both of them, something like a platform specific main() implementation where

- unix defaults to nofork=false, checks arguments and picks the cli or gui main depending on the value
- mac os is identical to unix except the default nofork is conditional on the stdin tty
- windows ignores nofork and just goes into the ui version

I am also wondering if we can adopt the mac os behavior in all unix and avoid the ifdef entirely, but i would need to think a bit further about it.

**Pull request merged**
