### PR TITLE
Show additional information in the popup menu

### PR DESCRIPTION
**Pull request by equalsraf**
ref https://github.com/equalsraf/neovim-qt/issues/441

### CODE REVIEW

**Comment by equalsraf** [comment]
@clason this should handle feature parity.

**Comment by clason** [comment]
Yeah, sorry, I saw too late that this was a bug, not a "not yet implemented". Please ignore my comment about opt-in vs. opt-out.

**Comment by equalsraf** [comment]
I've fixed the order. But I cant change the padding right away.

**Comment by clason** [comment]
Thank you! I'll see about the padding; I believe the padding is already introduced by the plugin before the information is passed to the pum (at least for some fields), so it might be that `QString` strips the spaces or somesuch.

**Comment by equalsraf** [comment]
See https://github.com/equalsraf/neovim-qt/pull/443 for implementing a custom delegate for the pum. At that point you can implement whatever widget or layout you want.

**Pull request merged**
