### PR TITLE
GUI: Support the reverse attribute in highligh_set

### PR DESCRIPTION
**Pull request by equalsraf**
For #128.

### CODE REVIEW

**Comment by JasonXJ** [comment]
Just tried it. Working great!

But I found a new problem. The color of underline is different in nvim-qt. Here is an example of `man ls` in the terminal emulator.

xx

**Comment by equalsraf** [comment]
I cannot reproduce here but it could be related to #121. @AdnoC should the special color be used for underline? https://github.com/equalsraf/neovim-qt/pull/121/files#diff-4f97cc211d81b6e872ac37bae6f5c5e4R152

It seems plausible the special color could be set, but the underline should always use the foreground color right?

**Comment by equalsraf** [comment]
Maybe this works for the underline issue

```diff
diff --git a/src/gui/shellwidget/shellwidget.cpp b/src/gui/shellwidget/shellwidget.cpp                              
index 0d51698..aaaf0b2 100644                                                                                       
--- a/src/gui/shellwidget/shellwidget.cpp                                                                           
+++ b/src/gui/shellwidget/shellwidget.cpp
@@ -148,18 +148,23 @@ void ShellWidget::paintEvent(QPaintEvent *ev)
                                // Draw "undercurl" at the bottom of the cell
                                if (cell.underline || cell.undercurl) {
                                        QPen pen = QPen();
-                                       // Use specail color if it is set, otherwise use foreground color
-                                       if (cell.specialColor.isValid()) {
-                                               pen.setColor(cell.specialColor);
-                                       } else if (m_spColor.isValid()) {
-                                               pen.setColor(m_spColor);
-                                       } else if (cell.foregroundColor.isValid()) {
-                                               pen.setColor(cell.foregroundColor);
-                                       } else {
-                                               pen.setColor(m_fgColor);
-                                       }
                                        if (cell.undercurl) {
+                                               if (cell.specialColor.isValid()) {
+                                                       pen.setColor(cell.specialColor);
+                                               } else if (m_spColor.isValid()) {
+                                                       pen.setColor(m_spColor);
+                                               } else if (cell.foregroundColor.isValid()) {
+                                                       pen.setColor(cell.foregroundColor);
+                                               } else {
+                                                       pen.setColor(m_fgColor);
+                                               }
                                                pen.setStyle(Qt::DashDotDotLine);
+                                       } else if (cell.underline) {
+                                               if (cell.foregroundColor.isValid()) {
+                                                       pen.setColor(cell.foregroundColor);
+                                               } else {
+                                                       pen.setColor(m_fgColor);
+                                               }
                                        }
 
                                        // TODO: draw a proper undercurl
```

**Comment by JasonXJ** [comment]
Yes, that works. By the way, if you would like to reproduce the problem yourself, you could first use `-u none` to disable settings and then use `:colorscheme desert` in nvim-qt.

**Pull request merged**
