### PR TITLE
Add option guifontwide

### PR DESCRIPTION
**Pull request by jgehrig**
**Issue #544:** Set alternative wide-character font.
**Pull #676:** Used as a starting point, refactored to keep a clean diff.

guifontwide_screen_recording

@yehuohan

Sorry for the silence on this feature... This is how I envision `guifontwide` operating in `neovim-qt`:

1. `:GuiFontWide` is no longer necessary, since `guifontwide` exists.

2. The option `guifontwide` can be tolerant of mono-space issues. Disregard invalid fonts at runtime.

3. We should use this as an opportunity to add test coverage for font conversion.

The refactor is done before any implementation work on `gufontwide`, commits:
fb22912 83fcd17 e9411ab

With these changes you could cleanly implement `guifontwide`.

**Option A:** I check in the refactor, and you finish up `guifontwide`. Your changes would be re-based on top.

**Option B:** You're tired of working on this... I can finish the work for the entire feature.

Let me know... I don't want to steal your feature, my intent is only to help :)

### CODE REVIEW

**Comment by yehuohan** [comment]
I think your commit is perfect and I'd perfer that you can finish the work.
I build the branch ` jgehrig:jg-guifontwide`, which worked well for me.

> The option guifontwide can be tolerant of mono-space issues. Disregard invalid fonts at runtime.

This point is cool. With this I can set font and wide-font just in init.vim but not using `GuiFont!` command at `VimEnter` to avoid reporting `bad fixed pitch metrics` .

**Comment by yehuohan** [comment]
I think it's a good idea that performing the cell's bold and italic attributes to the widefont in the function `ShellWidget::GetCellFont`. A simple code like below :)

```
	if (fontHasCharacter) {
		if (cell.IsBold() || cell.IsItalic()) {
			QFont cellFont{ wideFont };
			cellFont.setBold(cell.IsBold());
			cellFont.setItalic(cell.IsItalic());
			return cellFont;
		}
		return wideFont;
	}
```

**Comment by jgehrig** [comment]
Sounds good. I will pick up where you left off and get this checked-in.

> I think it's a good idea that performing the cell's bold and italic attributes to the widefont in the function ShellWidget::GetCellFont

Good catch! That is definitely a bug...

**Comment by jgehrig** [comment]
Interesting bug... It looks like the fix for Issue #575 does not propagate through `QVariant`. Fixed.

The call to `setStyleName("")` has been moved to before render-time in `ShellWidget::paintEvent`. In this location, we only need to clear this value once. Some of the other properties are required for fixed-pitch validation to work.

I did validate that all other properties translate from `QVariant` to `QFont`.

**Comment by jgehrig** [comment]
Testing help would be appreciated on this issue.

I only speak English, so I am not particularly familiar with multi-byte characters or corner cases in the usage of `guifontwide`.

**Pull request merged**
