### PR TITLE
Bump AppVeyor to Qt 5.15.0

### PR DESCRIPTION
**Pull request by jgehrig**
The AppVeyor Qt version used to generate Windows builds is old.

Update to the latest available version of Qt, 5.15.0.

### CODE REVIEW

**Comment by jgehrig** [comment]
Issue #733 Color Emojis are only rendered in recent versions of Qt.

Not working in 5.11.3. Tested working in 5.13.0.

**Comment by jgehrig** [comment]
@equalsraf

It looks like the Qt version bump causes an interesting bug with `windeployqt`. I reproduced on AppVeyor and one of my Windows machines. Error message `Unable to find the platform plugin.` during build.

It looks like an instance of this:
https://bugreports.qt.io/browse/QTBUG-62103

I think the fix (cc7eb13) is to remove `--release`, `--debug`, etc. However, I am not very familiar with Qt + Windows packaging.

Perhaps we want to scope this fix to only the impacted Qt releases? Any thoughts? Do you see any issues with the workaround?

**Comment by equalsraf** [comment]
The story for debug/release libraries in msvc really is very different from mingw, I was not even aware the options would have an effect for mingw builds.

Instead of outright removing this, we can just disable this for the MinGW generator e.g. https://github.com/equalsraf/neovim-qt/commit/b769ecc944886f85bb9cab2af825dce10e71c88f, I expect them to still be needed for MSVC debug builds.

I took the mingw appveyor build and they worked without problems, so i think we are good on that front.

**Comment by jgehrig** [comment]
Sounds good. Your change b769ecc looks like a better approach. I will cherry pick it into the PR and handle the merge.

I will also file a bug for tracking. The option may require a re-enable or re-address if Qt fixes this in the future.

**Pull request merged**
