### PR TITLE
Enable HiDpi scalling

### PR DESCRIPTION
**Pull request by equalsraf**

### CODE REVIEW

**Comment by equalsraf** [comment]
Tested this with linux multimonitor. It did not notice any difference :D

**Comment by equalsraf** [comment]
Well apparently this does not work on windows https://github.com/equalsraf/neovim-qt/issues/391#issuecomment-420066543

**Comment by equalsraf** [comment]
@youngmit pushing a new build, kind of a dirty hack but hopefully this one will work for windows.

**Comment by equalsraf** [comment]
In *theory* it should be ok. Based on the Qt docs and open issues in their bugtracker we might run into other issues depending on which APIs we are using, that may or may not return the expected sizes (e.g. the is multiplied by a factor).

For now I only enabled this for Windows. There are some more open [issues](https://bugreports.qt.io/browse/QTBUG-52196?jql=status%20in%20(Open%2C%20Reported)%20AND%20text%20~%20%22HiDPI%22) in windows and other systems. The most significant in our case would be related to widget positions and maybe icons, since we dont use opengl.

**Comment by stu-b-doo** [comment]
Is this fix available yet? I'm facing issue #391 . Not really sure how to build it from source to test it out

**Pull request merged**
