### PR TITLE
Make mingw32-make test on windows when qt5-static supported

### PR DESCRIPTION
**Pull request by zhaozg**
Fix some test code missing static link platform support

### CODE REVIEW

**Comment by equalsraf** [comment]
Can you rebase the the two commits into a single one?

Also, if possible, can you run the tests in the static build script, with

```batch
ctest -VV
```

**Comment by zhaozg** [comment]
ctest --VV fail
```
$ ctest -VV                                                                  
UpdateCTestConfiguration  from :E:/work/extra/neovim-qt/DartConfiguration.tcl
UpdateCTestConfiguration  from :E:/work/extra/neovim-qt/DartConfiguration.tcl
Test project E:/work/extra/neovim-qt                                         
Constructing a list of tests                                                 
Updating test list for fixtures                                              
Added 0 tests to meet fixture requirements                                   
Checking test dependency graph...                                            
Checking test dependency graph end                                           
No tests were found!!!                                                       
```

**Comment by equalsraf** [comment]
:+1: thanks @zhaozg

**Comment by zhaozg** [comment]
You are welcome.

**Pull request merged**
