### PR TITLE
Set initial editor size properly

### PR DESCRIPTION
**Pull request by jgehrig**
**Pull Request #866:** Set initial editor size properly

Created to rebase + merge #866.

Slight modifications required due to #875.

### CODE REVIEW

**Comment by jgehrig** [comment]
@statiolake

This is a rebase-only... Your changes unmodified.

I did notice some flicker on startup:
Startup

Do you see this flicker? I don't think this fixes #212...

With the PR above, startup was flicker-free. The changes as written are not compatible with each other.

Ideally, we would fix both issues. If we have to pick only one, proper startup size is definitely more important.

**Comment by statiolake** [comment]
Does "flicker" in your screenshot mean the initial intro message shown for a moment? If so, I don't notice such a flicker on Windows, but that might be hidden under its opening window animation. Note that usually I'm using `shortmess+=I` so I'm not bothered by it in daily life.

Instead I see the blank window on startup and I see it for a longer time with my patch. I didn't cared about it because it is common in Windows applications to have a blank window right after opening. GVim also has this kind of flicker. (As a side note, GVim has more "dynamic" flicker, since it keeps the lines and columns instead of window size. `set guifont` causes window resize.)

At least, in terms of flicker, this PR doesn't improve anything. It even removes the delaying mechanism introduced to reduce flickers.

For now I don't have a better way to achieve both of flickerless startup and proper editor size. We need to postpone displaying the window until everything gets ready to remove flicker. But we need to show the window before starting Neovim instance to know exact window size to determine the initial editor size.

A possible hacky way is to use saved geometry or explicitly specified value to estimate the next window size. We can expect the next window size is same with the previous window, as we are already trying to restore geometry on startup. But the window size request is not always satisifiable so actual window size may differ from the expectation. In that case the editor size will be still broken.

**Comment by jgehrig** [comment]
@statiolake 

Thanks for the detailed explanation. This all sounds reasonable.

Yes, I think `shortmess+=I` would eliminate the flicker I see.

> Instead I see the blank window on startup and I see it for a longer time with my patch.

Not a problem. I think proper startup size is much more important than increased blank-window time.

I view blank-window display as a non-issue. The critical metric (IMO) is startup time, and I don't think your changes have a significant effect on overall startup time.

**Side Note:**
At some point, I would like to write a CI rule that measures the startup-time differences between baseline and PR.
Measuring startup is critical to improving/preventing scenarios like your Issue #614.

> At least, in terms of flicker, this PR doesn't improve anything.

Not a problem, just curious.

> A possible hacky way

No need, I'd rather have clean code with some flicker.

**Comment by jgehrig** [comment]
@statiolake 

During some pre-merge testing, I discovered we don't account for space taken by `GuiScrollBar`, `GuiTabline`, or `GuiTreeView`.

We need to expand upon cafc9ca9f03e7f4104cc81c0330ae220e5f23497, and include additional options such as `Gui/ScrollBar`. Once we ensure that last known state for each of these controls is set, we can determine the correct size of `Shell` on startup.

Some flicker is caused by GUI widgets (we can fix this). The rest is due to the intro message, #808 #197 (we can ignore this).

Let me know how you'd like to handle these fixes.

**Comment by statiolake** [comment]
I've completely forgot about them since I don't show them at all...

Let me confirm my understanding. GUI widgets shown after initialization through init.vim's `:Gui*` commands change the editor size after Neovim splits the editor. For example, `GuiTreeviewShow` expands tree view from the left side of the editor, so the vertical split bar seems off to the right as a result. (I couldn't confirm it on my side because `GuiTreeviewShow` always filled up entire window size... Maybe I did something wrong.)

If that is true, as you said, just including their states in QSettings automatically solves this issue too.

I wish I could implement restoring those widgets by myself, but I'm not sure I have enough time to do it...

**Comment by jgehrig** [comment]
@statiolake

> I've completely forgot about them since I don't show them at all...

Yes, me too... Otherwise, I would have caught this sooner.

Your understanding of widget behavior sounds correct to me.

That `:GuiTreeView` behavior is a bug. The widget should not behave like that. I think the issue is gone in `master`?

> I wish I could implement restoring those widgets by myself, but I'm not sure I have enough time to do it...

Not a problem :)

I'll take care of the issues and merge your changes from this PR. I wanted to ask before modifying your code...

**Comment by statiolake** [comment]
> Not a problem :)
>
> I'll take care of the issues and merge your changes from this PR. I wanted to ask before modifying your code...

Thank you as always. Although I think changing QSettings should be in another PR, I'm fine with modifications by you.

**Comment by jgehrig** [comment]
> Although I think changing QSettings should be in another PR

Yes, I'll split things up. Probably all within the same PR, but different commits. Same end result :)

Assuming all goes smoothly with the `:Gui` issues, I'll try to get this merged within the next few days.

Thank you for yet another great (and much needed) improvement!

**Comment by jgehrig** [comment]
@statiolake 

Update, I haven't forgotten about this PR :)

I've noticed some issues when the window is restored from a previously maximized state... The initial size reported by Qt is not correct. I am trying to understand exactly what is going wrong, but it is not yet clear to me.

I'm delaying the merge until I better understand a root cause.

**Comment by statiolake** [comment]
Sorry for late reply.

> I've noticed some issues when the window is restored from a previously maximized state...

Could you tell me how to test it? Just now I tested branch `jgehrig:jg-editor-size` on Windows but I didn't notice the problem. I confirmed that `nvim-qt -- -O a b` correctly shows the maximized window divided vertically.

**Comment by jgehrig** [comment]
@statiolake

No worries.

The "issue" here is subtle. I'm not even sure it results in a perceivable difference...

If you look at the debug logs, you multiple calls to `handleResize: X Y` with different values before settling at a final size.

**Repro Steps:** (tested on Linux)
1. Open nvim-qt, maximize window, close
2. Re-open nvim-qt
3. Notice the `handleResize` messages report multiple different sizes. The first is incorrect.

If you do the same set of steps without the window previously maximized, the size is reported correctly immediately.

Note: Windows doesn't print `qDebug()` messages by default. I think you'll need to set `NVIM_QT_LOG`.

**Comment by jgehrig** [comment]
@statiolake 

Sorry for the LONG delay here...

I've merged your fix. I know lots of users will appreciate this, it has appeared in the Issue Tracker several times.

Thanks for your contributions! :+1:

**Pull request merged**
