### PR TITLE
Fix issue #237

### PR DESCRIPTION
**Pull request by equalsraf**
Fix expression quoting when changing the &rtp using nvim CLI
arguments.

As suggested by @justinmk.

### CODE REVIEW

**Comment by justinmk** [comment]
There's another case on line 208.

**Comment by xelra** [comment]
I've built it already with the third line also quoted, like @justinmk suggested. Unfortunately it doesn't fix #237.

**Comment by xelra** [comment]
I've played all day with the code and on my system the `neovimArgs` in the return statement look like this `--cmd let &rtp.=',C:\Program Files (x86)\Neovim-Qt\share\nvim-qt\runtime' --cmd set termguicolors` when joined and separated with whitespace. This looks right to me. Somewhere after that the path gets truncated to `C:\Program`.

**Comment by xelra** [comment]
Actually I've manually changed the `neovimArgs` and it didn't have any effect on the runtimepath. So I think the `C:\Program` doesn't even come from Neovim-Qt, at least not from this function.

My current hypothesis is that the `C:\Program` comes from somewhere else and that the `C:\Program Files (x86)\Neovim-Qt\share\nvim-qt\runtime` from `NVIM_QT_RUNTIME_PATH` doesn't get added to the runtimepath at all.

**Comment by equalsraf** [comment]
> My current hypothesis is that the C:\Program comes from somewhere else and that the C:\Program Files (x86)\Neovim-Qt\share\nvim-qt\runtime from NVIM_QT_RUNTIME_PATH doesn't get added to the runtimepath at all.

Well it should try three different things in this order:

1. If $NVIM_QT_RUNTIME_PATH is set use that
2. if NVIM_QT_RUNTIME_PATH is defined by the preprocessor then use that. This one comes from the CMake install path https://github.com/equalsraf/neovim-qt/blob/67f796dad544abf61cce5ae7e3ce5b8131a226dc/src/gui/CMakeLists.txt#L26
3. Relative to the nvim-qt binary as ../share/nvim-qt/runtime

> My current hypothesis is that the C:\Program comes from somewhere else 

Can you test with nvim by itself and see what happens. From a console:

    nvim --cmd "echo &rtp | q"

**Comment by justinmk** [comment]
```
C:\Program Files\Neovim>nvim --cmd "echo &rtp | q"
C:\Users\jkeyes\AppData\Local\nvim,C:\Users\jkeyes\AppData\Local\nvim\site,C:/Program Files (x86)/nvim/share/nvim,C:\Users\jkeyes\AppData\Local\nvim\site\after,C:\Users\jkeyes\AppData\Local\nvim\after
```

**Comment by xelra** [comment]
I just hard reseted to this PR again and now it works. I could have sworn I had tried `"let &rtp.=',%1'"` everywhere.

**Comment by justinmk** [comment]
Let's close this then.

**Comment by equalsraf** [comment]
Great. Thanks for taking the time @xelra.

**Pull request merged**
