### PR TITLE
Support for GUI popup menu

### PR DESCRIPTION
**Pull request by equalsraf**
Check https://github.com/neovim/neovim/pull/4432 for upstream WIP on allowing the GUI to handle the popup menu.

Indirectly this PR ended up holding other fixes too. Some of these are not backward compatible i.e. this only works with  neovim >= 0.1.5

### CODE REVIEW

**Comment by teto** [comment]
hi, anything I can do to help with this ? Having some example of what how to override neovim UI would be nice in master. I myself would be interested in "smart-UI-izing" the command line ':'.

**Comment by equalsraf** [comment]
A couple different problems here

1. the pum api is only available in 0.1.6dev
2. I haven't implemented a decent UI for this yet.

**Comment by teto** [comment]
Any plan to just merge the new neovim "attach" version ? I would take over if the commits were not so intertwined.
I will have lots of time in January and would like to play with https://github.com/neovim/neovim/pull/5686/files and UI fold externalization for instance.
Of course if you are too busy in these festive times, just ignore me :)

**Comment by equalsraf** [comment]
Moved to https://github.com/equalsraf/neovim-qt/pull/349.  @teto sorry I dropped the ball on this one.

**Comment by teto** [comment]
It's not like I helped either so np ^^
I trust you to make the popup menu great again.

**Pull request closed without merging**
