### PR TITLE
Release v0.2.17

### PR DESCRIPTION
**Pull request by equalsraf**
ref https://github.com/equalsraf/neovim-qt/issues/988

The process goes like this

1. Update CMakelists.txt project version to the release you want and commit it into master
2. tag the release in git - this will publish windows builds in the Releases page
3. once the release is complete, update CMakelists.txt again to mark it with 9999 tweak version and commit it again to master

You can test the process without touching the master branch using the **staging** tag. I have already started it for this PR

- staging build https://ci.appveyor.com/project/equalsraf/neovim-qt/builds/43830622 - artifacts will be available in the Releases page but check their date to be sure you are not downloading an earlier version.

### CODE REVIEW

**Comment by equalsraf** [comment]
Seeing some build failures here

- in appveyor one test is failing, I tried to increase the timeout but no change
- in azure the build step is failing, very little output, maybe this `'nvim' is not recognized as an internal or external command,`

**Comment by equalsraf** [comment]
The azure failure was just a change in the neovim package that changed the path.

**Comment by jgehrig** [comment]
Thanks for the instructions @equalsraf!

Let me know if you'd like to offload any of this work... I'd be happy to help, otherwise I will let you continue to work through this release.

> 'nvim' is not recognized as an internal or external command,

If I remember correctly, the directories within the `Neovim` release changed slightly. The `PATH` value needs to be updated. I think I fixed this for GitHub Actions already.

https://github.com/equalsraf/neovim-qt/blob/990b5bf5e3d19dc42839a29dd252e5c3dac70e40/.github/workflows/build-test.yml#L101

https://github.com/equalsraf/neovim-qt/commit/990b5bf5e3d19dc42839a29dd252e5c3dac70e40#diff-063ca77e012f959eba648db60e6868875fd1e70e5f5ac081193d848f8d61ef32

> 6: FAIL!  : NeovimQt::TestShell::guiShimCommands() 'SPYWAIT(cmd_gf2, 5000)' returned FALSE. ()
6: C:\projects\neovim-qt\test\tst_shell.cpp(147) : failure location

I think this failure is related to `:GuiFont XYZ` and `:set guifont=XYZ` updating each other. #977 

It might be worth reverting: https://github.com/equalsraf/neovim-qt/commit/06b40dda38518a827f0e870d7768fcf36c453a4a

There may also be some signal issues there. I remember for some startup cases extra `fontChanged` signals can be emitted when the default and user-selected fonts are set.

**Comment by equalsraf** [comment]
The path issue is already sorted

> I think this failure is related to :GuiFont XYZ and :set guifont=XYZ updating each other. https://github.com/equalsraf/neovim-qt/issues/977

I was suspecting something like this, I have been trying to force a change to happen before that test takes place. Let me give it a few more tries, otherwise i will need to boot up windows.

**Comment by justinmk** [comment]
> The process goes like this

I've found it to be very effective to maintain a "Release" section in the readme to document the release steps. Even just for reminding myself.

**Comment by equalsraf** [comment]
This one is weirder than I expected. It looks like msgpack request is not actually reaching neovim, the finished/error signal is not fired

https://ci.appveyor.com/project/equalsraf/neovim-qt/builds/43860981/job/jyenjii953rtcqev

**Comment by equalsraf** [comment]
Finally had some alone time with windows. Still was not able to troubleshoot this properly but the core of issue is some of the GuiFont commands failing due to bad metrics - what what making this difficult was that the first one to fail was not the one related to the font attributes, so in the end I changed all of them.

Time to cleanup so we can move forward.

**Comment by equalsraf** [comment]
Updated the wiki https://github.com/equalsraf/neovim-qt/wiki/Release-Process

**Comment by equalsraf** [comment]
Seeing a couple of other issues

1. appveyor is failing to upload artifacts 401
2. circle-ci tests are now failing - neovimconnector

**Comment by equalsraf** [comment]
The appveyor issue seems to be solved, a new release marked staging is in the releases page. If anyone gets a chance to test it before I do let me know.

I'm going to have a look at the other CI issues.

**Comment by equalsraf** [comment]
The CI issues are sorted, I am merging all this into master. The staging release is in the releases page, if no issues arise that will become v0.2.17 once it gets tagged.

I'll post updates under https://github.com/equalsraf/neovim-qt/issues/988

**Pull request merged**
