### PR TITLE
Fix unicode surrogate chars in shellwidget

### PR DESCRIPTION
**Pull request by equalsraf**
The shell widget is backed up by QChar, a 16bit char. For surrogate
chars this is problematic because we are painting char by char, but
painting a surrogate requires painting it as a whole.

To address this we allow storing the low surrogate inside the cell and
add Cell::text() that returns accordingly.

### CODE REVIEW

**Comment by equalsraf** [comment]
The biggest downside to this PR is that we run into rendering issues with some chars (e.g. for #140) when using a Neovim version earlier 0.1.5 - This is not a consequence of this PR, it happens because neovim and neovim-qt don't agree about the width of the characters.

I will hold the PR until 0.1.5 is released.

**Comment by jamessan** [comment]
Is this ready to be revisited now?  Note, I also just merged the `'emoji'` related patches from Vim (c.f., neovim/neovim#5372) which may have an impact.

**Comment by suy** [comment]
Hi.

I want to apologize for the stupid advice I gave on #140. It is true that for the given character in the issue one single QChar won't work, and two QChars would do, because it's a code point that needs two code units in QString. However, assuming that one code point is going to be displayed in one single glyph is wrong, and I don't know why I did not realize at that time. Here is one example of [one emoji that I get texted often](http://emojipedia.org/woman-facepalming/): 

```
$ uniscribe 🤦🏻♀

  1F926 ├─ 🤦            ├─ FACE PALM
  1F3FB ├─ 🏻            ├─ EMOJI MODIFIER FITZPATRICK TYPE-1-2
   200D ├─ ][           ├─ ZERO WIDTH JOINER
   2640 ├─ ♀            ├─ FEMALE SIGN
```
As you can see, that should be rendered as one single glyph, but it would fit in no less than 6 QChars (2 for face palm + 2 for the modifier + 1 for the ZWJ + 1 for the sign).

So, as you can see, I don't think adding more QChars is going to be a solution. I don't know if there is a theoretical limit for how many code points can be necessary for a single glyph.

I think the only proper solution for all the rendering issues is using a whole QString for the line,and letting QPainter do it's job of text shaping. Otherwise, is not going to be correct for languages [with complex text layout](https://en.wikipedia.org/wiki/Complex_text_layout).

**Comment by equalsraf** [comment]
> I think the only proper solution for all the rendering issues is using a whole QString for the line,and letting QPainter do it's job of text shaping. Otherwise, is not going to be correct for languages with complex text layout.

I agree. This was after all the same approach used in vim-qt.

The main difference here is that the nvim API may ask us to place (**put**) a string at an arbitrary cursor position in the line - i.e. we still need a way to map chars (or substrings) to screen cells, so that later we can perform a substitution.

I guess  the correct back end storage would be

- 1 QString per line
- An array of cell indexes that maps cells to QString indexes (if this even makes sense)

On a side note this particular example renders as separate chars in nvim and vim, two double-width chars (🤦🏻 turns into two, one that is not rendered by my terminal) and one single width (♀).

PS: optimisations likely require QStringRef QString::midRef()

**Comment by jgehrig** [comment]
Wide character rendering works now. We no longer use `QChar` within `Cell` either.

Marking as closed.

**Pull request closed without merging**
