### PR TITLE
Add GuiAdaptiveFont GuiAdaptiveColor

### PR DESCRIPTION
**Pull request by jgehrig**
Inspired by Pull Request #517

This adds the commands `:GuiAdaptiveFont` and `:GuiAdaptiveColor` which each make the Qt GUI respond to the current Neovim theme.

Specific logic was added to `:GuiPopupmenu` uses the `Pmenu` highlight group.

**Screenshot:**
GuiAdaptiveFontColor

### CODE REVIEW

**Comment by jgehrig** [comment]
There is still some small work left to do...

- Windows Testing
- MacOS Testing
- General code review/cleanup
- Documentation in nvim_gui_shim

Also, should this feature be ON by default?

I think many users dislike `GuiPopupmenu` and `GuiTabline` because the Qt theming does not line up with their Neovim theme. On Windows this is especially noticeable because the default font is very small.

**Comment by jgehrig** [comment]
@equalsraf 

The CircleCI failure looks related to Pull #716 and the test coverage report. Any ideas what is happening here?

**Comment by jgehrig** [comment]
**MacOS Screenshot:**
image

It looks like the `QPalette` theming for certain UI elements is ignored on MacOS/Windows. It looks like this is determined by the implementation details of the active Qt style.

A compatible style could be forced `QStyleFactory::create("Fusion")` across all platforms when `:GuiAdaptiveColor 1`. Alternatively, we could allow the user to specify a Qt Theme.

Unfortunately, each platform will required settings for an optimal 'out-of-the-box' experience... I need to think about this more.

**Comment by equalsraf** [comment]
I have no idea what the CI error is about, still searching.

> Unfortunately, each platform will required settings for an optimal 'out-of-the-box' experience... I need to think about this more.

I suspect runtime Qt stylesheets might be the only way to work around the platform issues. 
Maybe it is easier to generate some qss when color font changes and apply it to the main window.

**Comment by jgehrig** [comment]
I haven't found a way to resolve the QPalette or QStyleSheet native style themeing on MacOS/Windows.

Instead, I have added to option to override the default styling, `:GuiAdaptiveStyle Fusion`. A non-default theme will accept QPallette themeing. Even with the native widgets, a `colorscheme` could be carefully crafted to work with the native UI.

We won't be able to turn this on-by-default unfortunately, but I think that is fine.

**Pull request merged**
