### PR TITLE
Fix ctest run in github workflow/windows

### PR DESCRIPTION
**Pull request by equalsraf**
Testing fix for https://github.com/equalsraf/neovim-qt/issues/884

### CODE REVIEW

**Comment by equalsraf** [comment]
The checks are not starting for this PR

**Comment by equalsraf** [comment]
Windows tests are running now, but one of them is failing.

**Comment by equalsraf** [comment]
Enabled https://github.com/marketplace/actions/debugging-with-tmate for that windows job, which gave ssh into the runner.

I cannot get ctest to output verbose messages, e.g.

```
runneradmin@fv-az34-474 MINGW64 /d/a/neovim-qt/neovim-qt/build
# ctest -VV -C Release
UpdateCTestConfiguration  from :D:/a/neovim-qt/neovim-qt/build/DartConfiguration.tcl
UpdateCTestConfiguration  from :D:/a/neovim-qt/neovim-qt/build/DartConfiguration.tcl
Test project D:/a/neovim-qt/neovim-qt/build
Constructing a list of tests
Done constructing a list of tests
Updating test list for fixtures
Added 0 tests to meet fixture requirements
Checking test dependency graph...
Checking test dependency graph end
test 1
      Start  1: tst_neovimobject

1: Test command: D:\a\neovim-qt\neovim-qt\build\bin\tst_neovimobject.exe
1: Test timeout computed to be: 10000000
 1/19 Test  #1: tst_neovimobject .................   Passed    1.56 sec
test 2
      Start  2: tst_neovimconnector

2: Test command: D:\a\neovim-qt\neovim-qt\build\bin\tst_neovimconnector.exe
2: Test timeout computed to be: 10000000
 2/19 Test  #2: tst_neovimconnector ..............   Passed    8.34 sec
test 3
      Start  3: tst_callallmethods

(...)
```

The best I could do was output logs to a file

```
 # bin/test_shellcontents.exe -vs -o test.log
```

which has

```
********* Start testing of Test *********
Config: Using QtTest library 5.15.2, Qt 5.15.2 (x86_64-little_endian-llp64 shared (dynamic) debug build; by MSVC 2019), windows server2016
INFO   : Test::initTestCase() Signal: QThread(21e7f583060) started ()
PASS   : Test::initTestCase()
PASS   : Test::cellDefault()
RESULT : Test::cellDefault():
     0.36 msecs per iteration (total: 94, iterations: 256)
QWARN  : Test::resize() Invalid shell size -10 -10
QWARN  : Test::resize() Invalid shell size 0 0
FAIL!  : Test::resize() Compared values are not the same
   Actual   (s.value(i, j).GetCharacter()): 32
   Expected (uint('a'+j))                 : 97
D:\a\neovim-qt\neovim-qt\src\gui\shellwidget\test\test_shellcontents.cpp(113) : failure location
PASS   : Test::resizeBench()
RESULT : Test::resizeBench():
     0.000024 msecs per iteration (total: 51, iterations: 2097152)
FAIL!  : Test::clearRow() Compared values are not the same
   Actual   (s.value(i, j).GetCharacter()): 32
   Expected (uint('a'+j))                 : 135
D:\a\neovim-qt\neovim-qt\src\gui\shellwidget\test\test_shellcontents.cpp(156) : failure location
PASS   : Test::clearRowBench()
RESULT : Test::clearRowBench():
     0.0097 msecs per iteration (total: 80, iterations: 8192)
FAIL!  : Test::clearRegion() Compared values are not the same
   Actual   (s.constValue(i, j).GetCharacter()): 32
   Expected (uint('a'+j))                      : 154
D:\a\neovim-qt\neovim-qt\src\gui\shellwidget\test\test_shellcontents.cpp(33) : failure location
FAIL!  : Test::clearRegion() Compared values are not the same
D:\a\neovim-qt\neovim-qt\src\gui\shellwidget\test\test_shellcontents.cpp(204) : failure location
PASS   : Test::clearAll()
FAIL!  : Test::scrollRegion() Compared values are not the same
   Actual   (s.constValue(i, j).GetCharacter()): 32
   Expected (uint('a'+j))                      : 154
D:\a\neovim-qt\neovim-qt\src\gui\shellwidget\test\test_shellcontents.cpp(33) : failure location
FAIL!  : Test::scrollRegion() Compared values are not the same
   Actual   (s2.value(i, j).GetCharacter()): 32
   Expected (uint('a'+i+10))               : 107
D:\a\neovim-qt\neovim-qt\src\gui\shellwidget\test\test_shellcontents.cpp(261) : failure location
PASS   : Test::scrollRegion2()
INFO   : Test::put() Signal: QFile(eabd9ea1a8) aboutToClose ()
INFO   : Test::put() Signal: QFile(eabd9ea1a8) aboutToClose ()
INFO   : Test::put() Signal: QFile(eabd9ea1a8) aboutToClose ()
INFO   : Test::put() Signal: QFile(eabd9ea1a8) aboutToClose ()
INFO   : Test::put() Signal: QFile(eabd9ea1a8) aboutToClose ()
INFO   : Test::put() Signal: QFile(eabd9ea1a8) aboutToClose ()
INFO   : Test::put() Signal: QFile(eabd9ea1a8) aboutToClose ()
INFO   : Test::put() Signal: QFile(eabd9ea1a8) aboutToClose ()
INFO   : Test::put() Signal: QFile(eabd9ea1a8) aboutToClose ()
INFO   : Test::put() Signal: QFile(eabd9ea1a8) aboutToClose ()
INFO   : Test::put() Signal: QFile(eabd9ea1a8) aboutToClose ()
INFO   : Test::put() Signal: QFile(eabd9ea1a8) aboutToClose ()
INFO   : Test::put() Signal: QFile(eabd9ea1a8) aboutToClose ()
INFO   : Test::put() Signal: QFile(eabd9ea1a8) aboutToClose ()
INFO   : Test::put() Signal: QFile(eabd9ea1a8) aboutToClose ()
INFO   : Test::put() Signal: QFile(eabd9ea1a8) aboutToClose ()
INFO   : Test::put() Signal: QFile(eabd9ea1a8) aboutToClose ()
INFO   : Test::put() Signal: QFile(eabd9ea1a8) aboutToClose ()
INFO   : Test::put() Signal: QFileDevice(21e01ae44c0) aboutToClose ()
PASS   : Test::put()
PASS   : Test::cases()
PASS   : Test::cleanupTestCase()
INFO   : Test::UnknownTestFunc() Signal: QThread(21e7f583060) finished ()
Totals: 9 passed, 6 failed, 0 skipped, 0 blacklisted, 1209ms
********* Finished testing of Test *********
(END)
```

**Comment by equalsraf** [comment]
In general it seems that the test tries to grab the shell content, but instead of getting the expected characters it gets a space (32) - like the shell was not being populated.

**Comment by jgehrig** [comment]
@equalsraf

Hopefully, you don't mind me poking your branch :)

I've found a workaround for the test-failure-output issue!

It looks like something about the GitHub Actions environment is causing issues for qtest  executables using the `txt+stdout` format. Using a different output format such as `-tap` triggers readable output. I've added a CMake variable, so we can conditionally set that argument.

The MSVC `test_shellcontents` issues are odd. I'm not sure what causes that yet...

---

For our future reference, here is your (very useful) YML TMate debug snippet:
```yml
      - name: Setup tmate session
        if: ${{ failure() }}
        uses: mxschmitt/action-tmate@v3
```

**Comment by jgehrig** [comment]
It looks like the `tst_shell` failures are related to #898.

The behavior of the `neovimAttachmentChanged` signal changed, and this broke tests. A call to `->show()` is now required.

I didn't notice this Windows failure because AppVeyor went down due to some Neovim path changes, 1151c6dd45cb5f455165937dc47af2aaafeae4bf.

**Comment by jgehrig** [comment]
If we can get GitHub Actions working reliably, it would be nice to consolidate the CI jobs...

Perhaps we could remove CircleCI/AppVeyor/AzurePipelines after some period of time?

If we do consolidate, I think we would want to keep all CIs in place for some period of time and number of commits. That would ensure the results all match.

**Comment by equalsraf** [comment]
> I've found a workaround for the test-failure-output issue!

Pure madness, maybe it is doing some detection based on the terminal.


> If we can get GitHub Actions working reliably, it would be nice to consolidate the CI jobs...

I'm ok with consolidation, I just was not expecting this kind of issues :S

> Perhaps we could remove CircleCI/AppVeyor/AzurePipelines after some period of time?

The windows builds are still coming from appveyor, so that would need to be moved too, other than that all good.

**Comment by equalsraf** [comment]
> The behavior of the neovimAttachmentChanged signal changed, and this broke tests. A call to ->show() is now required.

Concerning this one, ValidateNeovimConnection is always called after a call to show().

The shell contents failure seems like it found a space character in the cell instead of 'a'.

**Pull request closed without merging**
