### PR TITLE
[WIP] GUI: Set application icon in Windows

### PR DESCRIPTION
**Pull request by equalsraf**
For #48. Converted the png to ico using ImageMagick. I didn't get a chance to try the binary in Windows yet.

### CODE REVIEW

**Comment by equalsraf** [comment]
Worked, but the icon has a white background, need to check it later.

**Comment by equalsraf** [comment]
Updated the icon.

**Comment by equalsraf** [comment]
@prabirshrestha taskbar icon works here. Can you check the exe https://ci.appveyor.com/project/equalsraf/neovim-qt/build/340/artifacts

**Comment by equalsraf** [comment]
For completeness this is what I used (ImageMagick) `convert neovim.png -define icon:auto-resize=64,48,32,16 neovim.ico`

**Comment by prabirshrestha** [comment]
:+1: it works.

In future might want to support large icon files too but is good enough for now.

image

**Comment by equalsraf** [comment]
Nice, added larger sizes too, will merge in a bit.

**Pull request merged**
