### PR TITLE
Fix window resize issues

### LINKED ISSUE #21: Window startup size
When i startup the window is quite small, about 210x130 px. Is there a way to configure the startup size?

The greates problem is that i cannot see the error messages, just some gibberish pixels:

This is also the startup size.

### PR DESCRIPTION
**Pull request by equalsraf**
Fix #21 and #4.

### CODE REVIEW

**Comment by prabirshrestha** [comment]
While this is definitely lot better then what it used to be. I find it too big now.

image

I think this is due to the position. The height does seem to be the height of the screen including taskbar which is usually what we don't want since most of us might not have set the taskbar to autohide.

image

Width also seems to be the width of the screen if so I think the best position is 0,0. Or just start it in maximized mode and then remember the size and position when I re-open it later.

**Comment by equalsraf** [comment]
Agreed, the size difference should be the width/height of the window decorations (not the taskbar) but the window size is defined at attachment, so we can:

- as you said start maximized, but this is probably unintuitive for most people
- pick an arbitrary default size that sounds reasonable e.g. 2/3 width and height of the current screen
- if we find a way to measure window decoration sizes we can keep the current behavior, but this is trickier to get right ([like this](https://github.com/equalsraf/vim-qt/blob/master/src/gui_qt.cpp#L619)) because menubars/toolbars and internal widget styles take up space as well

**Comment by equalsraf** [comment]
Went with the easier option :smile:, just defined the window size as 2/3 of the screen size.

**Comment by prabirshrestha** [comment]
:+1: 2/3 seems reasonable. I don't like maximized state or small size like what default gvim does.

**Pull request merged**
