### PR TITLE
Debug #53

### PR DESCRIPTION
**Pull request by equalsraf**
Lets have a look at debugging the close window issue, I added a debug statement to the process exit event.

### CODE REVIEW

**Comment by justinmk** [comment]
During a (unrelated) debugging session I noticed that `os_inchar()` might get stuck waiting for input if the UI is detached and then a "press enter" prompt occurs or some other input wait. 

Might try removing removing all calls to ui_detach. Let nvim close the connection, and interpret that as "quit". Could listen to VimLeave to verify that the quit was intentional.

**Comment by xelra** [comment]
About verifying whether the quit was intentional, maybe that would solve https://github.com/equalsraf/neovim-qt/issues/247 in one fell swoop.

**Comment by equalsraf** [comment]
> About verifying whether the quit was intentional, maybe that would solve #247 in one fell swoop.

I was thinking the same. Pushed a couple commits, they seem to work for #247, but have not tested the windows issue yet.

**Comment by equalsraf** [comment]
This seems to fix it for windows too - or more accurately it works around it, there is probably some deeper issue on my side.

Anyway I've cleaned this PR, and will merge tomorrow. If it works well its probably worth a tag too.

**Comment by justinmk** [comment]
Tried https://ci.appveyor.com/api/buildjobs/w8bn10spxcorpour/artifacts/neovim-qt.zip

It works :)

**Pull request merged**
