### PR TITLE
Project tree

### PR DESCRIPTION
**Pull request by ferranpm**
I don't know if you're interested in having this but I think it's a nice feature to have.

### CODE REVIEW

**Comment by justinmk** [comment]
What's the benefit vs netrw ?

**Comment by suy** [comment]
On Friday 17 March 2017 14:24:08 Justin M. Keyes wrote:
> What's the benefit vs netrw ?

I think it should be pretty obvious. :-)

GUIs offer a superset of the features of CLIs if the implementation is right 
and complete. Yes, I would not merge this as-is, because it might lack a 
proper plan on how to change focus between the file manager and the editor 
(and other possible "features" or "panes", or whatever might be called), or at 
least that seemed so after a very quick review. But having a GUI with perfect 
keyboard-only usage is perfectly doable with Qt. My company implemented that 
for a Qt-based project, and I just published a blog post on the topic:

http://www.vikingsoft.eu/keyboard-navigation-and-the-event-system/

I imagine that was your concern.

**Comment by ferranpm** [comment]
I don't have any preference, but I like it, it's simple and works. I find nerdtree to be a bit cumbersome.

I'll take a look at @suy 's post and try and improve it.

**Comment by nbicalcarata** [comment]
This is awesome! Thank you so much for this!

captura de pantalla de 2018-02-07 19-22-04

**Comment by kidproquo** [comment]
This is very nice! Any chance of an update?

**Comment by tkdchen** [comment]
Is it possible to add multiple projects into this tree? It would be super nice to have it.

**Comment by equalsraf** [comment]
@gagbo generally speaking you should wait for neovimconnector::ready before calling neovimObject i.e. you cannot expect the object to be available before a connection with neovim has been established.

**Comment by gagbo** [comment]
I got it, I changed the code so that the constructor actually connects an "init callback" to the ready signal from NeovimConnector. I messed up the formatting too, so I'm currently using johnmcfarlane/unformat on the current masterto try and deduce a `.clang-format` to use locally, and I'll push again.

Do you prefer that I open a new PR, or maybe should I just send a PR to @ferranpm ?

**Pull request merged**
