### PR TITLE
GUI: Increase default timeout from 10 to 20s

### PR DESCRIPTION
**Pull request by equalsraf**
Originally reported in https://github.com/neovim/neovim/issues/7934#event-1449035408 by @adelarsq.

### CODE REVIEW

**Comment by adelarsq** [comment]
``nvim-qt --timeout 20000`` didn't work. _neovim-qt_ just waits for nearly 10 seconds.

**Comment by adelarsq** [comment]
@equalsraf  The problem is that the timeout argument is being ignored I think.

**Comment by equalsraf** [comment]
@adelarsq yeah it is being ignored for the initial setup. I'll need to fix that. Does the build from this PR help with your problem?

**Comment by adelarsq** [comment]
Still don't. But it loads more things (plugins) now:

image

On the logs shows that the editor was starting and was stopped:
```
Searching for "C:\Users\myuser\.vim\plugged\vim-maven-syntax\autoload/wintabs/element.vim"
Searching for "C:\Users\myuser.
```

**Pull request merged**
